Outline/Models/OutlineModels/Outline.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Challenge24.Models.ChallengeModels
{
    public class Outline
    {
        public int OutlineId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string CreaterId { get; set; }

        [DataType(DataType.Date)]
        public DateTime CreateDate { get; set; }

        public ICollection<Commen> Comments { get; set; }
        public ICollection<OutlineUser> OutlineUsers { get; set; }

        public Outline()
        {
            Comments = new List<Commen>();
            OutlineUsers = new List<OutlineUser>();

        }
    }
}

Outline/Component/CommentViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Challenge24.Data;
using Microsoft.EntityFrameworkCore;

namespace Challenge24.Component
{
    public class CommentViewComponent: ViewComponent
    {

        private readonly ApplicationDbContext _context;
        public CommentViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke(int OutlineId)
        {
            //var comments = _context.Outlines.Where(o => o.OutlineId == OutlineId).Include(c => c.Comments).AsNoTracking();
            var comments = _context.Comments.Where(c => c.OutlineId == OutlineId).Include(co => co.ApplicationUser);
            return View("Comment", comments);
        }
    }
}

Outline/Controllers/OutlineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Challenge24.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Challenge24.Data;
using Challenge24.Models.ChallengeModels;
namespace Challenge24.Controllers
{
    [Authorize]
    public class OutlineController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public OutlineController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Outlines.ToList());
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Outline outline)
        {
            outline.CreaterId = _userManager.GetUserId(User);
            _context.Outlines.Add(outline);
            outline.OutlineUsers.Add(new OutlineUser { OutlineId = outline.OutlineId, UserId = outline.CreaterId, Day = 1 });
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Outline outline = await _context.Outlines.FirstOrDefaultAsync(p => p.OutlineId == id);
                if (outline != null)
                    return View(outline);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Outline outline)
        {
            if (outline != null)
            {
                _context.Outlines.Update(outline);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        public async Task<IActionResult> Remove(int? id)
        {
            Outline outline = await _context.Outlines.FirstOrDefaultAsync(p => p.OutlineId == id);
            if (outline != null)
            {
                _context.Outlines.Remove(outline);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");

            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Show(int? id)
        {
            if (id != null)
            {
                var outlines =await _context.Outlines.Include(c => c.OutlineUsers).ThenInclude(sc => sc.ApplicationUser).ToListAsync();
                Outline outline = outlines.FirstOrDefault(p => p.OutlineId == id);
                var usersOfoutline = outline.OutlineUsers.Select(user => user.ApplicationUser).ToList();
                ViewData["Users"] = usersOfoutline;
                if (outline != null)
                    return View(outline);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Show(int OutlineId, String comment)
        {
            if ( comment!= null)
            {
                Commen comm = new Commen();
                comm.CommentText = comment;
                comm.ApplicationUser = await _userManager.GetUserAsync(User);
                comm.OutlineId = OutlineId;
                _context.Comments.Add(comm);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Show", OutlineId);
        }

        public async Task<IActionResult> Join(int? id)
        {
            if (id != null)
            {
                Outline outline = await _context.Outlines.FirstOrDefaultAsync(p => p.OutlineId == id);
                outline.OutlineUsers.Add(new OutlineUser { OutlineId = outline.OutlineId, UserId = _userManager.GetUserId(User) });
                _context.Outlines.Update(outline);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }

        public async Task<IActionResult> Comments(int? id)
        {
            if (id != null)
            {
                Outline outline = await _context.Outlines.FirstOrDefaultAsync(p => p.OutlineId == id);
                outline.OutlineUsers.Add(new OutlineUser { OutlineId = outline.OutlineId, UserId = _userManager.GetUserId(User) });
                _context.Outlines.Update(outline);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

Outline/Views/Outline/Add.cshtml
@model Challenge24.Models.ChallengeModels.Outline

@{
    ViewData["Title"] = "AddOutline";
}

<h2>Ad dOutline</h2>

<h4>Outline</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Outline/Views/Outline/Edit.cshtml
@model Challenge24.Models.ChallengeModels.Outline

@{
    ViewData["Title"] = "EditOutline";
}

<h2>EditChallenge</h2>

<h4>Challenge</h4>
<hr />
<div class="row">
    <div class="col-md-3">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OutlineId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<markdown>**hello**</markdown>
<div>
    <a asp-action="Index">Back to List</a>
</div>

Outline/Views/Outline/Index.cshtml
@using Challenge24.Models.ChallengeModels
@model IEnumerable<Outline>
@{
    ViewData["Title"] = "ShowOutline";
}

<table class="table">
    @foreach (var outline in Model)
    {
    <tr>
        <td></td>
        <td>
        <td><a asp-area="" asp-controller="Outline" asp-action="Show" asp-route-id="@outline.OutlineId" class="navbar-brand">@outline.Name</a></td>
        
        <td>@outline.Description</td>
        <td><a asp-area="" asp-controller="Outline" asp-action="Join" asp-route-id="@outline.OutlineId" class="navbar-brand">join</a></td>
        <td><a asp-area="" asp-controller="Outline" asp-action="Edit" asp-route-id="@outline.OutlineId" class="navbar-brand">Edit</a></td>
        <td><a asp-area="" asp-controller="Outline" asp-action="Remove" asp-route-id="@outline.OutlineId" class="navbar-brand">Remove</a></td>
    </tr>
    }
</table>

Outline/Views/Outline/Show.cshtml
@model Challenge24.Models.ChallengeModels.Outline

@{
    ViewData["Title"] = "Show";
}

<h2>Show</h2>

<div>
    <h4>Challenge</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd>
            <markdown>@Html.DisplayFor(model => model.Content)</markdown>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>


    </dl>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model.OutlineId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<div>
    <form asp-action="Show">
        <input type="hidden" id="ID" name="OutlineId" value="@Model.OutlineId">
        <input type="text" id="comment" name="comment">
        <input type="submit" >
    </form>
</div>

@await Component.InvokeAsync("Comment", new { @Model.OutlineId });

Outline/Views/Outline/ShowChallenges.cshtml
@using Challenge24.Models.ChallengeModels
@model IEnumerable<Outline>
@{
    ViewData["Title"] = "ShowChallenges";
}

<table class="table">
    @foreach (var outline in Model)
    {
        <tr>
            <td></td>
            <td>@outline.Name</td>
            <td>@outline.Description</td>
        </tr>
    }
</table>