Models/ChallengeModels/Challenge.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Challenge24.Models.ChallengeModels
{
    public class Challenge
    {
        public int ChallengeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Condition { get; set; }

        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }
        
        [DataType(DataType.Date)]
        public DateTime FinishDate { get; set; }
        public ICollection<ChallengeUser> ChallengeUsers { get; set; }
        
    }
}

Controllers/ChallengeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Challenge24.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Challenge24.Data;
using Challenge24.Models.ChallengeModels;

namespace Challenge24.Controllers
{
    [Authorize]
    public class ChallengeController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public ChallengeController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Challenges.ToList());
        }

        [HttpGet]
        public IActionResult AddChallenge()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddChallenge(Challenge challenge)
        {
            _context.Challenges.Add(challenge);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditChallenge(int? id)
        {
            if (id != null)
            {
                Challenge challenge = await _context.Challenges.FirstOrDefaultAsync(p => p.ChallengeId == id);
                if (challenge != null)
                    return View(challenge);
            }
            return NotFound();
        }

        public async Task<IActionResult> Remove(int? id)
        {
            Challenge challenge = await _context.Challenges.FirstOrDefaultAsync(p => p.ChallengeId == id);
            if (challenge != null)
            {
                _context.Challenges.Remove(challenge);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
    }
}

Views/Challenge/AddChallenge.cshtml
@model Challenge24.Models.ChallengeModels.Challenge

@{
    ViewData["Title"] = "AddChallenge";
}

<h2>AddChallenge</h2>

<h4>Challenge</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddChallenge">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Challenge/EditChallenge.cshtml
@model Challenge24.Models.ChallengeModels.Challenge

@{
    ViewData["Title"] = "EditChallenge";
}

<h2>EditChallenge</h2>

<h4>Challenge</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditChallenge">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ChallengeId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Condition" class="control-label"></label>
                <input asp-for="Condition" class="form-control" />
                <span asp-validation-for="Condition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input asp-for="FinishDate"  class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Challenge/Index.cshtml
@using Challenge24.Models.ChallengeModels
@model IEnumerable<Challenge>
@{
    ViewData["Title"] = "ShowChallenges";
}

<table class="table">
    @foreach (var challenge in Model)
    {
        <tr>
            <td></td>
            <td>@challenge.Name</td>
            <td>@challenge.Description</td>
            <td><a asp-area="" asp-controller="Challenge" asp-action="EditChallenge" asp-route-id="@challenge.ChallengeId" class="navbar-brand">Edit</a></td>
            <td><a asp-area="" asp-controller="Challenge" asp-action="Remove" asp-route-id="@challenge.ChallengeId" class="navbar-brand">Remove</a></td>
        </tr>
    }
</table>

Views/Challenge/ShowChallenges.cshtml
@using Challenge24.Models.ChallengeModels
@model IEnumerable<Challenge>
@{
    ViewData["Title"] = "ShowChallenges";
}

<table class="table">
    @foreach (var challenge in Model)
    {
        <tr>
            <td></td>
            <td>@challenge.Name</td>
            <td>@challenge.Description</td>
        </tr>
    }
</table>